CREATE TABLE IF NOT EXISTS attributes (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);