BEGIN;

ALTER TABLE brands ADD COLUMN IF NOT EXISTS title_farsi VARCHAR(255);

ALTER TABLE categories
ADD COLUMN IF NOT EXISTS title_farsi VARCHAR(255);

ALTER TABLE product_types
ADD COLUMN IF NOT EXISTS title_farsi VARCHAR(255);

COMMIT;